<?php

class CountryDesc
{
    public function getCountry() 
    {
        $country = [
        'ABK' => 'Włochy',
        'Alaplana' => 'Hiszpania',
        'Aparici' => 'Hiszpania',
        'Ape Ceramika' => 'Hiszpania',
        'Aragona' => 'Hiszpania',
        'Argenta' => 'Hiszpania',
        'Azteca' => 'Hiszpania',
        'Caesar' => 'Włochy',
        'Casalgranda Padana' => 'Włochy',
        'Ceramika Picasa' => 'Hiszpania',
        'Cercom' => 'Włochy',
        'Cerim' => 'Włochy',
        'CIFRE' => 'Hiszpania',
        'Coem' => 'Włochy',
        'Decovita' => 'Turcja',
        'Decus' => 'Hiszpania',
        'Del Conca' => 'Włochy',
        'Dell Arte' => 'Turcja',
        'El Casa' => 'Hiszpania',
        'Elios' => 'Włochy',
        'Emil Ceramiche' => 'Włochy',
        'Equipe' => 'Hiszpania',
        'Evo Ceramika' => 'Polska',
        'Fabresa' => 'Hiszpania',
        'Fioranese' => '',
        'Flaviker' => 'Włochy',
        'Florim' => 'Włochy',
        'Gardenia Ochidea' => 'Włochy',
        'Geotiles' => 'Hiszpania',
        'Grespania' => 'Hiszpania',
        'Imola' => 'Włochy',
        'Indie' => 'Indie',
        'Intermatex' => 'Hiszpania',
        'Keope' => 'Włochy',
        'Keraben' => 'Hiszpania',
        'Keros' => 'Hiszpania',
        'antic Colonial' => 'Hiszpania',
        'Laminam' => 'Włochy',
        'Mainzu' => 'Hiszpania',
        'Marazzi' => 'Włochy',
        'Mayolica' => 'Hiszpania',
        'Metropol' => 'Niemcy',
        'Navarti' => 'Hiszpania',
        'Newker' => 'Hiszpania',
        'Novabell' => 'Włochy',
        'Ornamenta' => 'Belgia',
        'Pamesa' => 'Hiszpania',
        'Pastorelli' => 'Włochy',
        'Peronda' => 'Hiszpania',
        'Piemme' => 'Włochy',
        'Porcelanosa' => 'Hiszpania',
        'Quintessenza' => 'Włochy',
        'Ragno' => 'Włochy',
        'Realonda' => 'Hiszpania',
        'Rex Ceramiche' => 'Włochy',
        'Roca' => 'Hiszpania',
        'Rondine' => 'Włochy',
        'Saloni' => 'Hiszpania',
        'Sant Agostino' => 'Włochy',
        'Sintesi' => 'Hiszpania',
        'Steuler' => 'Niemcy',
        'Supergres' => 'Włochy',
        'Taragona Ceramika' => 'Hiszpania',
        'Terra Tinta' => 'Włochy',
        'Venis' => 'Hiszpania',
        'Versace' => 'Włochy',
        'Vives' => 'Hiszpania',
        'Wow' => 'Hiszpania'
        ];
    }
}
?>